

__all__ = [
        # lunex.common
        'STATES',
        'IDD_CODES',
        'first',
        # lunex.common.coerce_types
        'clean_cc_number',
        'make_id_list',
        'safe_int',
        'get_int_param',
        'not_undefined',
        'cached_property',
        'is_int',
        'strip_diacritics',
        # lunex.common.custom_fields
        'BigIntegerField',
        # lunex.common.dates
        'BIWEEKLY',
        'BIWEEKLY15',
        'BLINK',
        'DAY',
        'FORTNIGHT',
        'MONTHLY',
        'QUARTERLY',
        'WEEK',
        'WEEKLY',
        'add_month',
        'calc_date',
        'ensure_datetime',
        'get_cycle_due',
        'next_date',
        'next_month_year',
        'parse_datetime',
        'previous_date',
        'next_cycle',
        'start_cycle',
        'iter_cycle',
        'iter_days',
        # lunex.common.debug
        'trace',
        # lunex.common.enum
        'Enum',
        # lunex.common.files
        'open_file',
        'file_lock',
        # lunex.common.httputils
        'simple_http_request',
        # lunex.common.modelutils
        'EncryptedField',
        # lunex.common.ranges
        'drange',
        'frange',
        'range_str_iter',
        'make_range_str',
        # lunex.common.record
        'Record',
        # lunex.common.resp
        'json_to_datetime',
        'TextResponse',
        'JsonResponse',
        'to_json_resp',
        'to_csv_resp',
        'bad_request',
        # lunex.common.sequtils
        'pairs',
        'popwhile',
        # lunex.common.serializer
        'serialize_graph',
        'deserialize_graph',
        # lunex.common.templatetags.lunextags
        'moneyfmt',
        'percentfmt',
        # lunex.common.users
        'user_in_a_group',
        'get_name',
        'all_permissions_required',
        # lunex.common.viewutils
        'ModelViews',
        # lunex.common.xmlutils
        'get_xml_attr',
        'xml_indent',
        'XmlWriter',
        ]


import re

from django.utils.translation import ugettext_lazy as _

from lunex.common.coerce_types import *
from lunex.common.custom_fields import *
from lunex.common.dates import *
from lunex.common.debug import *
from lunex.common.enum import *
from lunex.common.files import *
from lunex.common.httputils import *
from lunex.common.modelutils import *
from lunex.common.ranges import *
from lunex.common.record import *
from lunex.common.resp import *
from lunex.common.sequtils import *
from lunex.common.serializer import *
from lunex.common.templatetags.lunextags import moneyfmt, percentfmt
from lunex.common.users import *
from lunex.common.viewutils import *
from lunex.common.xmlutils import *


RE_NOTDIGIT = re.compile(r'\D')

# From http://www.usps.com/ncsc/lookups/abbr_state.txt
STATES = [
    (_('Uk'), _('Unknown')),
    (_('AL'), _('Alabama')),
    (_('AK'), _('Alaska')),
    (_('AS'), _('American Samoa')),
    (_('AZ'), _('Arizona')),
    (_('AR'), _('Arkansas')),
    (_('CA'), _('California')),
    (_('CO'), _('Colorado')),
    (_('CT'), _('Connecticut')),
    (_('DE'), _('Delaware')),
    (_('DC'), _('District of Columbia')),
    (_('FM'), _('Federated States of Micronesia')),
    (_('FL'), _('Florida')),
    (_('GA'), _('Georgia')),
    (_('GU'), _('Guam')),
    (_('HI'), _('Hawaii')),
    (_('ID'), _('Idaho')),
    (_('IL'), _('Illinois')),
    (_('IN'), _('Indiana')),
    (_('IA'), _('Iowa')),
    (_('KS'), _('Kansas')),
    (_('KY'), _('Kentucky')),
    (_('LA'), _('Louisiana')),
    (_('ME'), _('Maine')),
    (_('MH'), _('Marshall Islands')),
    (_('MD'), _('Maryland')),
    (_('MA'), _('Massachusetts')),
    (_('MI'), _('Michigan')),
    (_('MN'), _('Minnesota')),
    (_('MS'), _('Mississippi')),
    (_('MO'), _('Missouri')),
    (_('MT'), _('Montana')),
    (_('NE'), _('Nebraska')),
    (_('NV'), _('Nevada')),
    (_('NH'), _('New Hampshire')),
    (_('NJ'), _('New Jersey')),
    (_('NM'), _('New Mexico')),
    (_('NY'), _('New York')),
    (_('NC'), _('North Carolina')),
    (_('ND'), _('North Dakota')),
    (_('MP'), _('Northern Mariana Islands')),
    (_('OH'), _('Ohio')),
    (_('OK'), _('Oklahoma')),
    (_('OR'), _('Oregon')),
    (_('PW'), _('Palau')),
    (_('PA'), _('Pennsylvania')),
    (_('PR'), _('Puerto Rico')),
    (_('RI'), _('Rhode Island')),
    (_('SC'), _('South Carolina')),
    (_('SD'), _('South Dakota')),
    (_('TN'), _('Tennessee')),
    (_('TX'), _('Texas')),
    (_('UT'), _('Utah')),
    (_('VT'), _('Vermont')),
    (_('VI'), _('Virgin Islands')),
    (_('VA'), _('Virginia')),
    (_('WA'), _('Washington')),
    (_('WV'), _('West Virginia')),
    (_('WI'), _('Wisconsin')),
    (_('WY'), _('Wyoming')),
    (_('AE'), _('Armed Forces Africa')),
    (_('AA'), _('Armed Forces Americas')),
    (_('AE'), _('Armed Forces Canada')),
    (_('AE'), _('Armed Forces Europe')),
    (_('AE'), _('Armed Forces Middle East')),
    (_('AP'), _('Armed Forces Pacific')),
    ]

# International Direct Dialing Codes
# lifted off wikipedia
IDD_CODES = [
    ('93', 'Afghanistan'),
    ('355', 'Albania'),
    ('213', 'Algeria'),
    ('1684', 'American Samoa'),
    ('376', 'Andorra'),
    ('244', 'Angola'),
    ('1264', 'Anguilla'),
    ('672', 'Antarctica'),
    ('1268', 'Antigua and Barbuda'),
    ('54', 'Argentina'),
    ('374', 'Armenia'),
    ('297', 'Aruba'),
    ('61', 'Australia'),
    ('43', 'Austria'),
    ('994', 'Azerbaijan'),
    ('1242', 'Bahamas'),
    ('973', 'Bahrain'),
    ('880', 'Bangladesh'),
    ('1246', 'Barbados'),
    ('375', 'Belarus'),
    ('32', 'Belgium'),
    ('501', 'Belize'),
    ('229', 'Benin'),
    ('1441', 'Bermuda'),
    ('975', 'Bhutan'),
    ('591', 'Bolivia'),
    ('387', 'Bosnia and Herzegovina'),
    ('267', 'Botswana'),
    ('55', 'Brazil'),
    ('246', 'British Indian Ocean Territory'),
    ('1284', 'British Virgin Islands'),
    ('673', 'Brunei Darussalam'),
    ('359', 'Bulgaria'),
    ('226', 'Burkina Faso'),
    ('257', 'Burundi'),
    ('855', 'Cambodia'),
    ('237', 'Cameroon'),
    ('238', 'Cape Verde'),
    ('1345', 'Cayman Islands '),
    ('236', 'Central African Republic'),
    ('235', 'Chad'),
    ('56', 'Chile'),
    ('86', 'China'),
    ('57', 'Colombia'),
    ('269', 'Comoros'),
    ('242', 'Congo (Brazzaville)'),
    ('243', 'Congo, Democratic Republic of the Congo'),
    ('682', 'Cook Islands '),
    ('506', 'Costa Rica'),
    ('225', 'Cote d''Ivoire'),
    ('385', 'Croatia'),
    ('53', 'Cuba'),
    ('357', 'Cyprus'),
    ('420', 'Czech Republic'),
    ('45', 'Denmark'),
    ('253', 'Djibouti'),
    ('1767', 'Dominica'),
    ('1809', 'Dominican Republic'),
    ('593', 'Ecuador'),
    ('20', 'Egypt'),
    ('503', 'El Salvador'),
    ('240', 'Equatorial Guinea'),
    ('291', 'Eritrea'),
    ('372', 'Estonia'),
    ('251', 'Ethiopia'),
    ('298', 'Faroe Islands'),
    ('679', 'Fiji'),
    ('358', 'Finland/Aland Islands'),
    ('33', 'France'),
    ('594', 'French Guiana'),
    ('689', 'French Polynesia'),
    ('241', 'Gabon'),
    ('220', 'Gambia'),
    ('995', 'Georgia'),
    ('49', 'Germany'),
    ('233', 'Ghana'),
    ('350', 'Gibraltar '),
    ('30', 'Greece'),
    ('299', 'Greenland'),
    ('1473', 'Grenada'),
    ('590', 'Guadeloupe/Saint-Martin/Saint-Barthelemy'),
    ('1671', 'Guam'),
    ('502', 'Guatemala'),
    ('441481', 'Guernsey'),
    ('224', 'Guinea'),
    ('245', 'Guinea-Bissau'),
    ('592', 'Guyana'),
    ('509', 'Haiti'),
    ('379', 'Holy See (Vatican City State)'),
    ('504', 'Honduras'),
    ('852', 'Hong Kong, Special Administrative Region of China'),
    ('36', 'Hungary'),
    ('354', 'Iceland'),
    ('91', 'India'),
    ('62', 'Indonesia'),
    ('98', 'Iran, Islamic Republic of Iran'),
    ('964', 'Iraq'),
    ('353', 'Ireland'),
    ('441624', 'Isle of Man '),
    ('972', 'Israel'),
    ('39', 'Italy'),
    ('1876', 'Jamaica'),
    ('81', 'Japan'),
    ('441534', 'Jersey'),
    ('962', 'Jordan'),
    ('77', 'Kazakhstan'),
    ('254', 'Kenya'),
    ('686', 'Kiribati'),
    ('850', 'Korea, Democratic People s Republic of Korea'),
    ('82', 'Korea, Republic of Korea'),
    ('383', 'Kosovo'),
    ('965', 'Kuwait'),
    ('996', 'Kyrgyzstan'),
    ('856', 'Lao PDR'),
    ('371', 'Latvia'),
    ('961', 'Lebanon'),
    ('266', 'Lesotho'),
    ('231', 'Liberia'),
    ('218', 'Libya'),
    ('423', 'Liechtenstein'),
    ('370', 'Lithuania'),
    ('352', 'Luxembourg'),
    ('853', 'Macao, Special Administrative Region of China'),
    ('389', 'Macedonia, Republic of Macedonia'),
    ('261', 'Madagascar'),
    ('265', 'Malawi'),
    ('60', 'Malaysia'),
    ('960', 'Maldives'),
    ('223', 'Mali'),
    ('356', 'Malta'),
    ('692', 'Marshall Islands'),
    ('596', 'Martinique'),
    ('222', 'Mauritania'),
    ('230', 'Mauritius'),
    ('52', 'Mexico'),
    ('691', 'Micronesia, Federated States of Micronesia'),
    ('373', 'Moldova'),
    ('377', 'Monaco'),
    ('976', 'Mongolia'),
    ('382', 'Montenegro'),
    ('1664', 'Montserrat'),
    ('212', 'Morocco'),
    ('258', 'Mozambique'),
    ('95', 'Myanmar'),
    ('264', 'Namibia'),
    ('674', 'Nauru'),
    ('977', 'Nepal'),
    ('31', 'Netherlands'),
    ('599', 'Netherlands Antilles/Curacao'),
    ('687', 'New Caledonia'),
    ('64', 'New Zealand'),
    ('505', 'Nicaragua'),
    ('227', 'Niger'),
    ('234', 'Nigeria'),
    ('683', 'Niue '),
    ('1670', 'Northern Mariana Islands'),
    ('47', 'Norway/Bouvet Island'),
    ('968', 'Oman'),
    ('92', 'Pakistan'),
    ('680', 'Palau'),
    ('970', 'Palestinian Territory, Occupied'),
    ('507', 'Panama'),
    ('675', 'Papua New Guinea'),
    ('595', 'Paraguay'),
    ('51', 'Peru'),
    ('63', 'Philippines'),
    ('48', 'Poland'),
    ('351', 'Portugal'),
    ('1787', 'Puerto Rico'),
    ('974', 'Qatar'),
    ('262', 'Reunion/Mayotte'),
    ('40', 'Romania'),
    ('7', 'Russian Federation'),
    ('250', 'Rwanda'),
    ('290', 'Saint Helena'),
    ('1869', 'Saint Kitts and Nevis'),
    ('1758', 'Saint Lucia'),
    ('508', 'Saint Pierre and Miquelon '),
    ('1784', 'Saint Vincent and Grenadines'),
    ('685', 'Samoa'),
    ('378', 'San Marino'),
    ('239', 'Sao Tome and Principe'),
    ('966', 'Saudi Arabia'),
    ('221', 'Senegal'),
    ('381', 'Serbia'),
    ('248', 'Seychelles'),
    ('232', 'Sierra Leone'),
    ('65', 'Singapore'),
    ('1721', 'Sint Maarten'),
    ('421', 'Slovakia'),
    ('386', 'Slovenia'),
    ('677', 'Solomon Islands'),
    ('252', 'Somalia'),
    ('27', 'South Africa'),
    ('211', 'South Sudan'),
    ('34', 'Spain'),
    ('94', 'Sri Lanka'),
    ('249', 'Sudan'),
    ('597', 'Suriname '),
    ('268', 'Swaziland'),
    ('46', 'Sweden'),
    ('41', 'Switzerland'),
    ('963', 'Syrian Arab Republic (Syria)'),
    ('886', 'Taiwan, Republic of China'),
    ('992', 'Tajikistan'),
    ('255', 'Tanzania , United Republic of'),
    ('66', 'Thailand'),
    ('228', 'Togo'),
    ('690', 'Tokelau '),
    ('676', 'Tonga'),
    ('1868', 'Trinidad and Tobago'),
    ('216', 'Tunisia'),
    ('90', 'Turkey'),
    ('993', 'Turkmenistan'),
    ('1649', 'Turks and Caicos Islands '),
    ('688', 'Tuvalu'),
    ('256', 'Uganda'),
    ('380', 'Ukraine'),
    ('971', 'United Arab Emirates'),
    ('44', 'United Kingdom'),
    ('1', 'United States of America'),
    ('598', 'Uruguay'),
    ('998', 'Uzbekistan'),
    ('678', 'Vanuatu'),
    ('84', 'Viet Nam'),
    ('1340', 'Virgin Islands, US'),
    ('967', 'Yemen'),
    ('260', 'Zambia'),
    ('263', 'Zimbabwe')

    # ('93', 'Afghanistan'),
    # ('355', 'Albania'),
    # ('213', 'Algeria'),
    # ('1684', 'American Samoa'),
    # ('376', 'Andorra'),
    # ('244', 'Angola'),
    # ('1264', 'Anguilla'),
    # ('1268', 'Antigua and Barbuda'),
    # ('54', 'Argentina'),
    # ('374', 'Armenia'),
    # ('297', 'Aruba'),
    # ('247', 'Ascension'),
    # ('61', 'Australia'),
    # ('672', 'Australian External Territories'),
    # ('43', 'Austria'),
    # ('994', 'Azerbaijan'),
    # ('1242', 'Bahamas'),
    # ('973', 'Bahrain'),
    # ('880', 'Bangladesh'),
    # ('1246', 'Barbados'),
    # ('375', 'Belarus'),
    # ('32', 'Belgium'),
    # ('501', 'Belize'),
    # ('229', 'Benin'),
    # ('1441', 'Bermuda'),
    # ('975', 'Bhutan'),
    # ('591', 'Bolivia'),
    # ('599', 'Bonaire/Curacao'),
    # ('387', 'Bosnia and Herzegovina'),
    # ('267', 'Botswana'),
    # ('55', 'Brazil'),
    # ('246', 'British Indian Ocean Territory'),
    # ('1284', 'British Virgin Islands'),
    # ('673', 'Brunei'),
    # ('359', 'Bulgaria'),
    # ('226', 'Burkina Faso'),
    # ('257', 'Burundi'),
    # ('855', 'Cambodia'),
    # ('237', 'Cameroon'),
    # # ('1', 'Canada'), # listed with US
    # ('238', 'Cape Verde'),
    # ('1345', 'Cayman Islands'),
    # ('236', 'Central African Republic'),
    # ('235', 'Chad'),
    # ('56', 'Chile'),
    # ('86', 'China'),
    # # ('61', 'Christmas Island'), # duplicate with australia
    # # ('61', 'Cocos-Keeling Islands'), # duplicate with australia
    # ('57', 'Colombia'),
    # ('269', 'Comoros'),
    # ('242', 'Congo'),
    # ('243', 'Congo Dem. Rep. of (Zaire)'),
    # ('682', 'Cook Islands'),
    # ('506', 'Costa Rica'),
    # ('385', 'Croatia'),
    # ('53', 'Cuba'),
    # # ('599', 'Curacao'), # duplicate with netherlands antilles
    # ('357', 'Cyprus'),
    # ('420', 'Czech Republic'),
    # ('45', 'Denmark'),
    # ('253', 'Djibouti'),
    # ('1767', 'Dominica'),
    # ('1809', 'Dominican Republic'),
    # # ('1809', 'Dominican Republic 1-809'),
    # # ('1829', 'Dominican Republic 1-829'),
    # # ('1849', 'Dominican Republic 1-849'),
    # ('670', 'East Timor'),
    # # ('56', 'Easter Island'), # duplicate with chile
    # ('593', 'Ecuador'),
    # ('20', 'Egypt'),
    # ('503', 'El Salvador'),
    # ('8812', 'Ellipso Mobile Satellite service 8812'),
    # ('8813', 'Ellipso Mobile Satellite service 8813'),
    # ('88213', 'EMSAT Mobile Satellite service'),
    # ('240', 'Equatorial Guinea'),
    # ('291', 'Eritrea'),
    # ('372', 'Estonia'),
    # ('251', 'Ethiopia'),
    # ('500', 'Falkland Islands'),
    # ('298', 'Faroe Islands'),
    # ('679', 'Fiji'),
    # ('358', 'Finland'),
    # ('33', 'France'),
    # ('594', 'French Guiana'),
    # ('689', 'French Polynesia'),
    # ('241', 'Gabon'),
    # ('220', 'Gambia'),
    # ('995', 'Georgia'),
    # ('49', 'Germany'),
    # ('233', 'Ghana'),
    # ('350', 'Gibraltar'),
    # ('30', 'Greece'),
    # ('299', 'Greenland'),
    # ('1473', 'Grenada'),
    # ('590', 'Guadeloupe/Saint Barthelemy/Saint Martin'),
    # ('1671', 'Guam'),
    # ('5399', 'Guantanamo Bay'),
    # ('502', 'Guatemala'),
    # ('245', 'Guinea-Bissau'),
    # ('224', 'Guinea'),
    # ('592', 'Guyana'),
    # ('509', 'Haiti'),
    # ('504', 'Honduras'),
    # ('852', 'Hong Kong SAR China'),
    # ('36', 'Hungary'),
    # ('354', 'Iceland'),
    # ('91', 'India'),
    # ('62', 'Indonesia'),
    # ('870', 'Inmarsat SNAC'),
    # ('800', 'International Freephone Service'),
    # ('808', 'International Shared Cost Service (ISCS)'),
    # ('98', 'Iran'),
    # ('964', 'Iraq'),
    # ('353', 'Ireland'),
    # ('972', 'Israel'),
    # ('39', 'Italy'),
    # ('225', 'Ivory Coast'),
    # ('1876', 'Jamaica'),
    # ('81', 'Japan'),
    # ('962', 'Jordan'),
    # ('77', 'Kazakhstan'),
    # ('254', 'Kenya'),
    # ('686', 'Kiribati'),
    # ('965', 'Kuwait'),
    # ('996', 'Kyrgyzstan'),
    # ('856', 'Laos'),
    # ('371', 'Latvia'),
    # ('961', 'Lebanon'),
    # ('266', 'Lesotho'),
    # ('231', 'Liberia'),
    # ('218', 'Libya'),
    # ('423', 'Liechtenstein'),
    # ('370', 'Lithuania'),
    # ('352', 'Luxembourg'),
    # ('853', 'Macau SAR China'),
    # ('389', 'Macedonia'),
    # ('261', 'Madagascar'),
    # ('265', 'Malawi'),
    # ('60', 'Malaysia'),
    # ('960', 'Maldives'),
    # ('223', 'Mali'),
    # ('356', 'Malta'),
    # ('692', 'Marshall Islands'),
    # ('596', 'Martinique'),
    # ('222', 'Mauritania'),
    # ('230', 'Mauritius'),
    # ('262', 'Mayotte/Reunion'), # duplicate with reunion
    # ('52', 'Mexico'),
    # ('99952', 'Mexico Bill Payment'),
    # ('691', 'Micronesia'),
    # # ('1808', 'Midway Island'), # part of hawaii
    # ('373', 'Moldova'),
    # ('377', 'Monaco'),
    # ('976', 'Mongolia'),
    # ('382', 'Montenegro'),
    # ('1664', 'Montserrat'),
    # ('212', 'Morocco'),
    # ('258', 'Mozambique'),
    # ('95', 'Myanmar'),
    # ('264', 'Namibia'),
    # ('674', 'Nauru'),
    # ('977', 'Nepal'),
    # ('31', 'Netherlands'),
    # ('687', 'New Caledonia'),
    # ('64', 'New Zealand'),
    # ('505', 'Nicaragua'),
    # ('227', 'Niger'),
    # ('234', 'Nigeria'),
    # ('683', 'Niue'),
    # # ('672', 'Norfolk Island'), # duplicate with Australian External Territories
    # ('850', 'North Korea'),
    # ('1670', 'Northern Mariana Islands'),
    # ('47', 'Norway'),
    # ('968', 'Oman'),
    # ('92', 'Pakistan'),
    # ('680', 'Palau'),
    # ('970', 'Palestinian Territory'),
    # ('507', 'Panama'),
    # ('675', 'Papua New Guinea'),
    # ('595', 'Paraguay'),
    # ('51', 'Peru'),
    # ('63', 'Philippines'),
    # ('48', 'Poland'),
    # ('351', 'Portugal'),
    # ('1787', 'Puerto Rico'),
    # ('1939', 'Puerto Rico 1-939'),
    # ('974', 'Qatar'),
    # ('40', 'Romania'),
    # ('7', 'Russia'),
    # ('250', 'Rwanda'),
    # # ('262', 'Reunion'), # listed with mayotte
    # # ('590', 'Saint Barthelemy'),  # listed with Guadeloupe
    # ('290', 'Saint Helena'),
    # ('1869', 'Saint Kitts and Nevis'),
    # ('1758', 'Saint Lucia'),
    # # ('590', 'Saint Martin'),      # listed with Guadeloupe
    # ('508', 'Saint Pierre and Miquelon'),
    # ('1784', 'Saint Vincent and the Grenadines'),
    # ('685', 'Samoa'),
    # ('378', 'San Marino'),
    # ('966', 'Saudi Arabia'),
    # ('221', 'Senegal'),
    # ('381', 'Serbia'),
    # ('248', 'Seychelles'),
    # ('232', 'Sierra Leone'),
    # ('65', 'Singapore'),
    # ('421', 'Slovakia'),
    # ('386', 'Slovenia'),
    # ('677', 'Solomon Islands'),
    # ('252', 'Somalia'),
    # ('27', 'South Africa'),
    # ('82', 'South Korea'),
    # ('34', 'Spain'),
    # ('94', 'Sri Lanka'),
    # ('249', 'Sudan'),
    # ('597', 'Suriname'),
    # ('268', 'Swaziland'),
    # ('46', 'Sweden'),
    # ('41', 'Switzerland'),
    # ('963', 'Syria'),
    # ('239', 'Sao Tome and Principe'),
    # ('886', 'Taiwan'),
    # ('992', 'Tajikistan'),
    # ('255', 'Tanzania'),
    # ('66', 'Thailand'),
    # ('228', 'Togo'),
    # ('690', 'Tokelau'),
    # ('676', 'Tonga'),
    # ('1868', 'Trinidad and Tobago'),
    # ('216', 'Tunisia'),
    # ('90', 'Turkey'),
    # ('993', 'Turkmenistan'),
    # ('1649', 'Turks and Caicos Islands'),
    # ('688', 'Tuvalu'),
    # ('1340', 'U.S. Virgin Islands'),
    # ('256', 'Uganda'),
    # ('380', 'Ukraine'),
    # ('971', 'United Arab Emirates'),
    # ('44', 'United Kingdom'),
    # #('1', 'United States/Canada'),
    # ('1', 'USA'),
    # ('878', 'Universal Personal Telecommunications (UPT)'),
    # ('598', 'Uruguay'),
    # ('998', 'Uzbekistan'),
    # ('678', 'Vanuatu'),
    # ('379', 'Vatican'),
    # ('58', 'Venezuela'),
    # ('84', 'Vietnam'),
    # # ('1808', 'Wake Island'), # part of hawaii?
    # ('681', 'Wallis and Futuna'),
    # ('967', 'Yemen'),
    # ('260', 'Zambia'),
    # ('263', 'Zimbabwe'),
    ]

#http://www.iso.org/iso/support/faqs/faqs_widely_used_standards/widely_used_standards_other/currency_codes/currency_codes_list-1.htm
CURR_CODES = [
    ('1', 'USA'),
    ('7', 'RUS'),
    ('20', 'EGY'),
    ('27', 'ZAF'),
    ('30', 'GRC'),
    ('31', 'NLD'),
    ('32', 'BEL'),
    ('33', 'FRA'),
    ('34', 'ESP'),
    ('36', 'HUN'),
    ('39', 'ITA'),
    ('40', 'ROU'),
    ('41', 'CHE'),
    ('43', 'AUT'),
    ('44', 'GBR'),
    ('45', 'DNK'),
    ('46', 'SWE'),
    ('47', 'NOR'),
    ('48', 'POL'),
    ('49', 'DEU'),
    ('51', 'PER'),
    ('52', 'MEX'),
    ('53', 'CUB'),
    ('54', 'ARG'),
    ('55', 'BRA'),
    ('56', 'CHL'),
    ('57', 'COL'),
    ('60', 'MYS'),
    ('61', 'AUS'),
    ('62', 'IDN'),
    ('63', 'PHL'),
    ('64', 'NZL'),
    ('65', 'SGP'),
    ('66', 'THA'),
    ('77', 'KAZ'),
    ('81', 'JPN'),
    ('82', 'KOR'),
    ('84', 'VNM'),
    ('86', 'CHN'),
    ('90', 'TUR'),
    ('91', 'IND'),
    ('92', 'PAK'),
    ('93', 'AFG'),
    ('94', 'LKA'),
    ('95', 'MMR'),
    ('98', 'IRN'),
    ('211', 'SSD'),
    ('212', 'MAR'),
    ('213', 'DZA'),
    ('216', 'TUN'),
    ('218', 'LBY'),
    ('220', 'GMB'),
    ('221', 'SEN'),
    ('222', 'MRT'),
    ('223', 'MLI'),
    ('224', 'GIN'),
    ('225', 'CIV'),
    ('226', 'BFA'),
    ('227', 'NER'),
    ('228', 'TGO'),
    ('229', 'BEN'),
    ('230', 'MUS'),
    ('231', 'LBR'),
    ('232', 'SLE'),
    ('233', 'GHA'),
    ('234', 'NGA'),
    ('235', 'TCD'),
    ('236', 'CAF'),
    ('237', 'CMR'),
    ('238', 'CPV'),
    ('239', 'STP'),
    ('240', 'GNQ'),
    ('241', 'GAB'),
    ('242', 'COG'),
    ('243', 'COD'),
    ('244', 'AGO'),
    ('245', 'GNB'),
    ('246', 'IOT'),
    ('248', 'SYC'),
    ('249', 'SDN'),
    ('250', 'RWA'),
    ('251', 'ETH'),
    ('252', 'SOM'),
    ('253', 'DJI'),
    ('254', 'KEN'),
    ('255', 'TZA'),
    ('256', 'UGA'),
    ('257', 'BDI'),
    ('258', 'MOZ'),
    ('260', 'ZMB'),
    ('261', 'MDG'),
    ('262', 'REU'),
    ('263', 'ZWE'),
    ('264', 'NAM'),
    ('265', 'MWI'),
    ('266', 'LSO'),
    ('267', 'BWA'),
    ('268', 'SWZ'),
    ('269', 'COM'),
    ('290', 'SHN'),
    ('291', 'ERI'),
    ('297', 'ABW'),
    ('298', 'FRO'),
    ('299', 'GRL'),
    ('350', 'GIB'),
    ('351', 'PRT'),
    ('352', 'LUX'),
    ('353', 'IRL'),
    ('354', 'ISL'),
    ('355', 'ALB'),
    ('356', 'MLT'),
    ('357', 'CYP'),
    ('358', 'FIN'),
    ('359', 'BGR'),
    ('370', 'LTU'),
    ('371', 'LVA'),
    ('372', 'EST'),
    ('373', 'MDA'),
    ('374', 'ARM'),
    ('375', 'BLR'),
    ('376', 'AND'),
    ('377', 'MCO'),
    ('378', 'SMR'),
    ('379', 'VAT'),
    ('380', 'UKR'),
    ('381', 'SRB'),
    ('382', 'MNE'),
    ('383', 'XKX'),
    ('385', 'HRV'),
    ('386', 'SVN'),
    ('387', 'BIH'),
    ('389', 'MKD'),
    ('420', 'CZE'),
    ('421', 'SVK'),
    ('423', 'LIE'),
    ('501', 'BLZ'),
    ('502', 'GTM'),
    ('503', 'SLV'),
    ('504', 'HND'),
    ('505', 'NIC'),
    ('506', 'CRI'),
    ('507', 'PAN'),
    ('508', 'SPM'),
    ('509', 'HTI'),
    ('590', 'GLP'),
    ('591', 'BOL'),
    ('592', 'GUY'),
    ('593', 'ECU'),
    ('594', 'GUF'),
    ('595', 'PRY'),
    ('596', 'MTQ'),
    ('597', 'SUR'),
    ('598', 'URY'),
    ('599', 'ANT'),
    ('672', 'ATA'),
    ('673', 'BRN'),
    ('674', 'NRU'),
    ('675', 'PNG'),
    ('676', 'TON'),
    ('677', 'SLB'),
    ('678', 'VUT'),
    ('679', 'FJI'),
    ('680', 'PLW'),
    ('682', 'COK'),
    ('683', 'NIU'),
    ('685', 'WSM'),
    ('686', 'KIR'),
    ('687', 'NCL'),
    ('688', 'TUV'),
    ('689', 'PYF'),
    ('690', 'TKL'),
    ('691', 'FSM'),
    ('692', 'MHL'),
    ('850', 'PRK'),
    ('852', 'HKG'),
    ('853', 'MAC'),
    ('855', 'KHM'),
    ('856', 'LAO'),
    ('880', 'BGD'),
    ('886', 'TWN'),
    ('960', 'MDV'),
    ('961', 'LBN'),
    ('962', 'JOR'),
    ('963', 'SYR'),
    ('964', 'IRQ'),
    ('965', 'KWT'),
    ('966', 'SAU'),
    ('967', 'YEM'),
    ('968', 'OMN'),
    ('970', 'PSE'),
    ('971', 'ARE'),
    ('972', 'ISR'),
    ('973', 'BHR'),
    ('974', 'QAT'),
    ('975', 'BTN'),
    ('976', 'MNG'),
    ('977', 'NPL'),
    ('992', 'TJK'),
    ('993', 'TKM'),
    ('994', 'AZE'),
    ('995', 'GEO'),
    ('996', 'KGZ'),
    ('998', 'UZB'),
    ('1242', 'BHS'),
    ('1246', 'BRB'),
    ('1264', 'AIA'),
    ('1268', 'ATG'),
    ('1284', 'VGB'),
    ('1340', 'VIR'),
    ('1345', 'CYM'),
    ('1441', 'BMU'),
    ('1473', 'GRD'),
    ('1649', 'TCA'),
    ('1664', 'MSR'),
    ('1670', 'MNP'),
    ('1671', 'GUM'),
    ('1684', 'ASM'),
    ('1721', 'SXM'),
    ('1758', 'LCA'),
    ('1767', 'DMA'),
    ('1784', 'VCT'),
    ('1787', 'PRI'),
    ('1809', 'DOM'),
    ('1868', 'TTO'),
    ('1869', 'KNA'),
    ('1876', 'JAM'),
    ('441481', 'GGY'),
    ('441534', 'JEY'),
    ('441624', 'IMN')


              # ('971', 'AFN'),
              # ('8', 'ALL'),
              # ('12', 'DZD'),
              # ('973', 'AOA'),
              # ('32', 'ARS'),
              # ('51', 'AMD'),
              # ('533', 'AWG'),
              # ('944', 'AZN'),
              # ('44', 'BSD'),
              # ('48', 'BHD'),
              # ('50', 'BDT'),
              # ('52', 'BBD'),
              # ('974', 'BYR'),
              # ('84', 'BZD'),
              # ('60', 'BMD'),
              # ('64', 'BTN'),
              # ('68', 'BOB'),
              # ('984', 'BOV'),
              # ('977', 'BAM'),
              # ('72', 'BWP'),
              # ('986', 'BRL'),
              # ('96', 'BND'),
              # ('975', 'BGN'),
              # ('108', 'BIF'),
              # ('116', 'KHR'),
              # ('124', 'CAD'),
              # ('132', 'CVE'),
              # ('136', 'KYD'),
              # ('152', 'CLP'),
              # ('990', 'CLF'),
              # ('156', 'CNY'),
              # ('170', 'COP'),
              # ('970', 'COU'),
              # ('174', 'KMF'),
              # ('976', 'CDF'),
              # ('188', 'CRC'),
              # ('191', 'HRK'),
              # ('192', 'CUP'),
              # ('931', 'CUC'),
              # ('203', 'CZK'),
              # ('262', 'DJF'),
              # ('214', 'DOP'),
              # ('818', 'EGP'),
              # ('222', 'SVC'),
              # ('232', 'ERN'),
              # ('233', 'EEK'),
              # ('230', 'ETB'),
              # ('238', 'FKP'),
              # ('242', 'FJD'),
              # ('950', 'XAF'),
              # ('270', 'GMD'),
              # ('981', 'GEL'),
              # ('936', 'GHS'),
              # ('292', 'GIP'),
              # ('208', 'DKK'),
              # ('320', 'GTQ'),
              # ('324', 'GNF'),
              # ('328', 'GYD'),
              # ('332', 'HTG'),
              # ('340', 'HNL'),
              # ('344', 'HKD'),
              # ('348', 'HUF'),
              # ('352', 'ISK'),
              # ('356', 'INR'),
              # ('360', 'IDR'),
              # ('364', 'IRR'),
              # ('368', 'IQD'),
              # ('376', 'ILS'),
              # ('388', 'JMD'),
              # ('392', 'JPY'),
              # ('400', 'JOD'),
              # ('398', 'KZT'),
              # ('404', 'KES'),
              # ('408', 'KPW'),
              # ('410', 'KRW'),
              # ('414', 'KWD'),
              # ('417', 'KGS'),
              # ('418', 'LAK'),
              # ('428', 'LVL'),
              # ('422', 'LBP'),
              # ('426', 'LSL'),
              # ('430', 'LRD'),
              # ('434', 'LYD'),
              # ('440', 'LTL'),
              # ('446', 'MOP'),
              # ('807', 'MKD'),
              # ('969', 'MGA'),
              # ('454', 'MWK'),
              # ('458', 'MYR'),
              # ('462', 'MVR'),
              # ('478', 'MRO'),
              # ('480', 'MUR'),
              # ('484', 'MXN'),
              # ('979', 'MXV'),
              # ('498', 'MDL'),
              # ('496', 'MNT'),
              # ('943', 'MZN'),
              # ('104', 'MMK'),
              # ('516', 'NAD'),
              # ('524', 'NPR'),
              # ('532', 'ANG'),
              # ('558', 'NIO'),
              # ('566', 'NGN'),
              # ('512', 'OMR'),
              # ('586', 'PKR'),
              # ('590', 'PAB'),
              # ('598', 'PGK'),
              # ('600', 'PYG'),
              # ('604', 'PEN'),
              # ('608', 'PHP'),
              # ('985', 'PLN'),
              # ('634', 'QAR'),
              # ('946', 'RON'),
              # ('643', 'RUB'),
              # ('646', 'RWF'),
              # ('654', 'SHP'),
              # ('951', 'XCD'),
              # ('882', 'WST'),
              # ('678', 'STD'),
              # ('682', 'SAR'),
              # ('941', 'RSD'),
              # ('690', 'SCR'),
              # ('694', 'SLL'),
              # ('702', 'SGD'),
              # ('90', 'SBD'),
              # ('706', 'SOS'),
              # ('710', 'ZAR'),
              # ('144', 'LKR'),
              # ('938', 'SDG'),
              # ('968', 'SRD'),
              # ('578', 'NOK'),
              # ('748', 'SZL'),
              # ('752', 'SEK'),
              # ('756', 'CHF'),
              # ('948', 'CHW'),
              # ('947', 'CHE'),
              # ('760', 'SYP'),
              # ('901', 'TWD'),
              # ('972', 'TJS'),
              # ('834', 'TZS'),
              # ('764', 'THB'),
              # ('952', 'XOF'),
              # ('554', 'NZD'),
              # ('776', 'TOP'),
              # ('780', 'TTD'),
              # ('788', 'TND'),
              # ('949', 'TRY'),
              # ('934', 'TMT'),
              # ('36', 'AUD'),
              # ('800', 'UGX'),
              # ('980', 'UAH'),
              # ('784', 'AED'),
              # ('826', 'GBP'),
              # ('998', 'USS'),
              # ('997', 'USN'),
              # ('858', 'UYU'),
              # ('940', 'UYI'),
              # ('860', 'UZS'),
              # ('548', 'VUV'),
              # ('978', 'EUR'),
              # ('937', 'VEF'),
              # ('704', 'VND'),
              # ('840', 'USD'),
              # ('953', 'XPF'),
              # ('504', 'MAD'),
              # ('886', 'YER'),
              # ('894', 'ZMK'),
              # ('932', 'ZWL'),
              # ('959', 'XAU'),
              # ('955', 'XBA'),
              # ('956', 'XBB'),
              # ('957', 'XBC'),
              # ('958', 'XBD'),
              # ('960', 'XDR'),
              # ('964', 'XPD'),
              # ('962', 'XPT'),
              # ('961', 'XAG'),
              # ('Nil', 'XFU'),
              # ('963', 'XTS'),
              # ('999', 'XXX'),
    ]

def first(iterator, default=None):
    for item in iterator: return item
    else: return default


def pprint_phone(phone_no):
    cleaned = RE_NOTDIGIT.sub('', phone_no)
    if len(cleaned) == 7:
        return '%s-%s' % (cleaned[:3], cleaned[3:])
    elif len(cleaned) == 10:
        return '(%s) %s-%s' % (cleaned[:3], cleaned[3:6], cleaned[6:])
    else:
        return phone_no


